Frank/datasink metadata
fair-acc/graph-prototype pull request #283
Opened 2024-02-22 22:45 UTC by frankosterfeld

Fix issues in DataSink:

Make sure lookup by signal_name is thread-safe and is not accessing the
signal_name member directly, which might be updated in another thread.

Simplify and fix the signal metadata propagation to work with the automatic forwarding of source properties matching default tags.

WIP until things are working in opendigitizer

2024-02-28 10:31 UTC, frankosterfeld commented on core/include/gnuradio-4.0/Scheduler.hpp
> +        emitMessage(msgOut, { { key::Kind, kind::SchedulerStateUpdate }, { key::What, std::string(magic_enum::enum_name(newState)) } });
Thinking about it, maybe `key::Data` instead of `key::What` should be used? @ivan-cukic do you have an opinion?

2024-03-01 09:17 UTC, frankosterfeld commented
For the question of how to handle the old init(...) (now performInit() in this PR) method vs. the state machine callback also called `init()` atm, also see https://github.com/fair-acc/graph-prototype/issues/289

2024-03-02 20:04 UTC, frankosterfeld commented on core/include/gnuradio-4.0/Scheduler.hpp
> +        emitMessage(msgOut, { { key::Kind, kind::SchedulerStateUpdate }, { key::What, std::string(magic_enum::enum_name(newState)) } });
done

2024-03-07 12:38 UTC, RalphSteinhagen requested changes
@frankosterfeld , thanks for the update. :+1: 

I like the `std::optional<U> getProperty(const property_map &m, std::string_view key);`. We should (separate PR) elevate this to using `std::expected<..>` and make this a core function or perhaps for the pmt-library itself as this is a common use case that I also saw @ivan-cukic introduced for the message handling. 

I also like the GRC-based loader-based unit-test in qa_Settings. Why is this disabled for Emscripten?
As discussed in the GR Architecture channel, this grc-file-based definition is good both for unit-tests as well as basic-usage documentation. We had a quick iteration over here, and maybe we will add another optional `using ... = fixed_string("grc definition");` to the blocks to allow for documenting these (at least the basic) use cases. Unit-tests and documentation aside, this could also be used on the GR website to launch a WASM GR UI for the block documentation where users could directly play/experiment with a give block.

Regarding the modifications to core library functions in Scheduler.hpp and Block.hpp (comments only), unless these changes address specific bugs or are critically needed, I suggest reverting them due to concurrent modifications being made in other PRs.

Your contributions are valuable, and with these minor adjustments, this PR could be merged. Thanks in advance.

2024-03-07 12:38 UTC, RalphSteinhagen commented on core/include/gnuradio-4.0/Block.hpp
> + * In addition derived classes can optionally implement any subset of the lifecycle methods ( `init()`, `start()`, `stop()`, `reset()`, `pause()`, `resume()`).
please revert

2024-03-07 12:38 UTC, RalphSteinhagen commented on core/include/gnuradio-4.0/Block.hpp
> + * void init() {...} // Implement any initialisation logic required for the block within this method.
and this.

2024-03-07 12:52 UTC, frankosterfeld commented on core/include/gnuradio-4.0/Scheduler.hpp
> +        emitMessage(msgOut, { { key::Kind, kind::SchedulerStateUpdate }, { key::Data, std::string(magic_enum::enum_name(newState)) } });
Well, it's not needed, I just think these messages are malformed (my fault, from the previous PR), and do not follow the intended pattern of key/value pairs, where the keys from the key:: namespace.

2024-03-07 12:58 UTC, frankosterfeld commented on core/include/gnuradio-4.0/Scheduler.hpp
> +        emitMessage(msgOut, { { key::Kind, kind::SchedulerStateUpdate }, { key::Data, std::string(magic_enum::enum_name(newState)) } });
reverted here, moved to https://github.com/fair-acc/graph-prototype/pull/294

2024-03-07 13:08 UTC, RalphSteinhagen approved these changes
@frankosterfeld thanks for the changes. Will squash-merge it once the CI passes.

2024-03-07 15:58 UTC, merged