Allow subscribing to lifecycle messages
fair-acc/graph-prototype pull request #304
Opened 2024-03-28 10:08 UTC by frankosterfeld

Make sure clients can subscribe to kLifeCycleState. For schedulers,
make sure subscriptions are processed before scheduler start, so that
clients receive all state changes.

2024-04-03 12:05 UTC, wirew0rm requested changes
Looks good, overall, thanks :+1:

2024-04-03 12:11 UTC, frankosterfeld commented on core/include/gnuradio-4.0/Scheduler.hpp
I've tried first to connect the messaging blocks in the constructor, which caused issues in qa_HierBlock (HierBlock impl is unfinished/tbd anyway, but could work around that) and qa_HttpBlock (didn't understand why it's failing - HttpBlock is using the builtin msgIn for control messages, which seems wrong). So this seemed the less intrusive approach. I also see the problem when connecting new blocks (and thus creating new readers/writers) while another thread might read/write messages, we'll have to make sure that it doesn't happen. CC @ivan-cukic , maybe he has an idea.

2024-04-03 12:12 UTC, frankosterfeld commented on core/include/gnuradio-4.0/Scheduler.hpp
> +                _toChildMessagePort.streamWriter().publish([&](auto &out) { std::ranges::copy(_pendingMessagesToChildren, out.begin()); }, _pendingMessagesToChildren.size());
Eh, indeed :) Will fix.

2024-04-03 13:42 UTC, ivan-cukic commented on core/include/gnuradio-4.0/Scheduler.hpp
In my head, as the scheduler knows when things are (not) processed, it can use that time to process the topology update requests. Though, Ralph might have something different in mind.

2024-04-04 13:06 UTC, wirew0rm approved these changes

2024-04-04 13:08 UTC, merged